services:
  - type: web
    name: app-flask
    env: python
    plan: free
    root: meu_projeto    # <-- aqui você informa a subpasta onde está o app e o requirements.txt
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
